import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Shared/Header";
import DoItRight from "@/Components/DoItRight";
import Banner from "@/Components/Home/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const rubik = Rubik({
  weight: ['300','400', '500', '600']

})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#E7E7E3] ${rubik.className}`}>
        <header className="w-full absolute top-8">
          <Header />
        </header>
        <main className="mt-40">
          <section>
            <DoItRight />
          </section>
          <section>
            <Banner/>
          </section>
          {children}
        </main>
      </body>
    </html>
  );
}
